[workspace]
authors = ["Igor Popov <ipopovi@gmail.com>"]
channels = ["conda-forge"]
name = "MLOps_for_DevOps2025"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pyarrow = ">=22.0.0,<23"
clearml = ">=2.1.2,<3"
nltk = ">=3.9.2,<4"
polars = ">=1.37.1,<2"
pandas = ">=2.3.3,<3"
plotly = ">=6.5.2,<7"
