services:
  streamlit-app:
    build: .
    container_name: clearml-streamlit-interface
    ports:
      - "8501:8501"
    env_file:
      - /opt/clearml/.env.common
#    environment:
#      - CLEARML_MODEL_API_URL=${CLEARML_MODEL_API_URL}
#      - CLEARML_API_ACCESS_KEY=${CLEARML_API_ACCESS_KEY}
#      - CLEARML_API_SECRET_KEY=${CLEARML_API_SECRET_KEY}
#      - STREAMLIT_SERVER_HEADLESS=true
    restart: unless-stopped
    networks:
      - clearml-network

networks:
  clearml-network:
    driver: bridge
